### ISSUE TITLE
can not access the server

### ISSUE THREAD

**Issue by pondwater** [gabe565/docker-obico#36]
so i am install ing this on trunas scale, the new one that moved away from k3s, the issue i am having is that since that machie is headless, i am unable to access localhost:3334 from the machine since it does not have a browser and sany browser i add via docker, has its own localhost so therefor unable to access the admin site,

i have tried accessing the shell of the web service and task service since they both have the manage.py
running the command "./manage.py site --add 192.168.1.254:3334" yields an error code

/app # ./manage.py site --add 192.168.1.254:3334
System check identified some issues:

![image](https://github.com/user-attachments/assets/9388fda4-f887-4fa3-8fdd-46a8d52cf56e)

this is the end of my experiance of what i can do and am stuck

WARNINGS:
app.User: (auth.W004) 'User.email' is named as the 'USERNAME_FIELD', but it is not unique.
        HINT: Ensure that your authentication backend(s) can handle non-unique usernames.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: app_syndicate

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/app/app/management/commands/site.py", line 23, in handle
    syndicate, _ = Syndicate.objects.get_or_create(name="base")
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: app_syndicate

**Comment by pondwater** [comment]
so after plugging away some more i did get it running on my trunas, but i had to first run it on my pc to have access to localhost:3334, logged in and made my setting on the admin page and added the site address of my server, after that moved all files to server and started it up on the server and i could access it from there, so if there is a way to add a site in an environment could save a lot of others a lot of pain

**Comment by DaKue77** [comment]
I recently ran into the same issue a few times already (also with the Obico official installation path) - must be related to some more recent changes in django since I did not run into this issue some time ago. Also seems to be a general issue with Django, not Obico related.

Anyway, I was able to fix it this way (replacing example.com with my domain name):

$> ./manage.py shell
>>> from django.contrib.sites.models import Site
>>> site = Site()
>>> site.domain = 'example.com'
>>> site.name = 'example.com'
>>> site.save()

The solution was found here:
https://stackoverflow.com/questions/16068518/django-site-matching-query-does-not-exist
